[package]
name = "lol_live"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.13", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1.49", features = ["full"] }
xcap = "0.8"
leptess = "0.14"
image = "0.25"
