on:
  push:
    branches:
      - '**'

name: Build and Check

jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y \
            libleptonica-dev \
            libtesseract-dev \
            tesseract-ocr \
            libwayland-dev \
            libwayland-bin \
            libwayland-client0 \
            libxkbcommon-dev \
            pkg-config

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache setup
        uses: Swatinem/rust-cache@v2

      - name: Cargo check
        run: cargo check

  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y \
            libleptonica-dev \
            libtesseract-dev \
            tesseract-ocr \
            libwayland-dev \
            libwayland-bin \
            libwayland-client0 \
            libxkbcommon-dev \
            pkg-config

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache setup
        uses: Swatinem/rust-cache@v2

      - name: Cargo test
        run: cargo test

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y \
            libleptonica-dev \
            libtesseract-dev \
            tesseract-ocr \
            libwayland-dev \
            libwayland-bin \
            libwayland-client0 \
            libxkbcommon-dev \
            pkg-config

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Rust cache setup
        uses: Swatinem/rust-cache@v2

      - name: Cargo fmt
        run: cargo fmt --all -- --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y \
            libleptonica-dev \
            libtesseract-dev \
            tesseract-ocr \
            libwayland-dev \
            libwayland-bin \
            libwayland-client0 \
            libxkbcommon-dev \
            pkg-config

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Rust cache setup
        uses: Swatinem/rust-cache@v2

      - name: Cargo clippy
        run: cargo clippy --all-features

  build:
    name: Build

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: aarch64-apple-darwin
    #          - os: macos-latest
    #            target: x86_64-apple-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install tesseract leptonica

      - name: Install system dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          vcpkg install leptonica:x64-windows-static-md
          vcpkg install tesseract:x64-windows-static-md
          echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV
        shell: bash

      - name: Rust cache setup
        uses: Swatinem/rust-cache@v2

      - name: Build
        shell: bash
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lol_live-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/lol_live${{ contains(matrix.target, 'windows') && '.exe' || '' }}
